### ISSUE TITLE
Development Roadmap

### ISSUE THREAD

**Issue by ManiMozaffar** [ManiMozaffar/omdbapi#1]
- [x] Sketch the design with design.io
- [x] Base HTTPX Core implementation
- [x] Base  Cralwer Design
- [x] Base Health Check/v1 design
- [x] OMDB repo
- [x] OMDB controller
- [x] OMDB routers
- [x] OMDB tests
- [x] Refactor and debug for tests
- [x] Dockerize
- [x] Doc string
- [x] Github action tests
- [x] Readme
- [x] LGTM!

:)

**Comment by ManiMozaffar** [comment]
DONE! :)
